TurtleResetsL = {}

-- --- ENGLISH (Default) ---
TurtleResetsL["en"] = {
    ["WINDOW_TITLE"] = "TurtleRaids Resets",
    ["TAB_STATUS"] = "Status",
    ["TAB_INSTANCE"] = "Instance",
    ["TAB_RESET"] = "Next Reset",
    ["LOCKED"] = "|cffff0000Locked|r",
    ["AVAIL"] = "|cff00ff00Available|r",
    ["DAYS"] = { [0]="Sunday", [1]="Monday", [2]="Tuesday", [3]="Wednesday", [4]="Thursday", [5]="Friday", [6]="Saturday" },
    ["OPT_TITLE"] = "Time Configuration",
    ["OPT_R40"] = "Raids 40 (Global Cycle)",
    ["OPT_ONY"] = "Onyxia's Lair",
    ["OPT_KARA"] = "Karazhan",
    ["OPT_R20"] = "Raids 20 (Global Cycle)",
    ["OPT_LANG"] = "Language:",
    ["LABEL_DAYS"] = "Days",
    ["LABEL_HOURS"] = "Hours",
    ["LABEL_MINUTES"] = "Minutes",
    ["BTN_SAVE"] = "Save Settings",
    ["BTN_CANCEL"] = "Cancel",
    ["TO_SET"] = "To set",
    ["SCAN_MC"] = "Molten Core",
    ["SCAN_BWL"] = "Blackwing Lair",
    ["SCAN_AQ40"] = "Temple of Ahn'Qiraj",
    ["SCAN_NAXX"] = "Naxxramas",
    ["SCAN_ES"] = "Emerald Sanctum", -- Ajout ES
    ["SCAN_ONY"] = "Onyxia",
    ["SCAN_KARA"] = "Karazhan",
    ["SCAN_ZG"] = "Zul'Gurub",
    ["SCAN_AQ20"] = "Ruins of Ahn'Qiraj",
}

-- --- FRANÇAIS ---
TurtleResetsL["fr"] = {
    ["WINDOW_TITLE"] = "Réinitialisations Turtle",
    ["TAB_STATUS"] = "Statut",
    ["TAB_INSTANCE"] = "Instance",
    ["TAB_RESET"] = "Prochain Reset",
    ["LOCKED"] = "|cffff0000Verrouillé|r",
    ["AVAIL"] = "|cff00ff00Disponible|r",
    ["DAYS"] = { [0]="Dimanche", [1]="Lundi", [2]="Mardi", [3]="Mercredi", [4]="Jeudi", [5]="Vendredi", [6]="Samedi" },
    ["OPT_TITLE"] = "Configuration du Temps",
    ["OPT_R40"] = "Raids 40 (Cycle Global)",
    ["OPT_ONY"] = "Le Repaire d'Onyxia",
    ["OPT_KARA"] = "Karazhan",
    ["OPT_R20"] = "Raids 20 (Cycle Global)",
    ["OPT_LANG"] = "Langue :",
    ["LABEL_DAYS"] = "Jours",
    ["LABEL_HOURS"] = "Heures",
    ["LABEL_MINUTES"] = "Minutes",
    ["BTN_SAVE"] = "Sauvegarder",
    ["BTN_CANCEL"] = "Annuler",
    ["TO_SET"] = "À config.",
    ["SCAN_MC"] = "Cœur du Magma",
    ["SCAN_BWL"] = "Repaire de l'Aile noire",
    ["SCAN_AQ40"] = "Temple d'Ahn'Qiraj",
    ["SCAN_NAXX"] = "Naxxramas",
    ["SCAN_ES"] = "Sanctum Émeraude", -- Ajout ES
    ["SCAN_ONY"] = "Onyxia",
    ["SCAN_KARA"] = "Karazhan",
    ["SCAN_ZG"] = "Zul'Gurub",
    ["SCAN_AQ20"] = "Ruines d'Ahn'Qiraj",
}

-- --- DEUTSCH ---
TurtleResetsL["de"] = {
    ["WINDOW_TITLE"] = "TurtleRaids Resets",
    ["TAB_STATUS"] = "Status",
    ["TAB_INSTANCE"] = "Instanz",
    ["TAB_RESET"] = "Nächster Reset",
    ["LOCKED"] = "|cffff0000Gesperrt|r",
    ["AVAIL"] = "|cff00ff00Verfügbar|r",
    ["DAYS"] = { [0]="Sonntag", [1]="Montag", [2]="Dienstag", [3]="Mittwoch", [4]="Donnerstag", [5]="Freitag", [6]="Samstag" },
    ["OPT_TITLE"] = "Zeitkonfiguration",
    ["OPT_R40"] = "Raids 40 (Globaler Zyklus)",
    ["OPT_ONY"] = "Onyxias Hort",
    ["OPT_KARA"] = "Karazhan",
    ["OPT_R20"] = "Raids 20 (Globaler Zyklus)",
    ["OPT_LANG"] = "Sprache:",
    ["LABEL_DAYS"] = "Tage",
    ["LABEL_HOURS"] = "Stunden",
    ["LABEL_MINUTES"] = "Minuten",
    ["BTN_SAVE"] = "Speichern",
    ["BTN_CANCEL"] = "Abbrechen",
    ["TO_SET"] = "Einstellen",
    ["SCAN_MC"] = "Geschmolzener Kern",
    ["SCAN_BWL"] = "Pechschwingenhort",
    ["SCAN_AQ40"] = "Tempel von Ahn'Qiraj",
    ["SCAN_NAXX"] = "Naxxramas",
    ["SCAN_ES"] = "Smaragdgrünes Sanktum", -- Ajout ES
    ["SCAN_ONY"] = "Onyxia",
    ["SCAN_KARA"] = "Karazhan",
    ["SCAN_ZG"] = "Zul'Gurub",
    ["SCAN_AQ20"] = "Ruinen von Ahn'Qiraj",
}

-- --- ESPAÑOL ---
TurtleResetsL["es"] = {
    ["WINDOW_TITLE"] = "Reinicios de Turtle",
    ["TAB_STATUS"] = "Estado",
    ["TAB_INSTANCE"] = "Instancia",
    ["TAB_RESET"] = "Siguiente",
    ["LOCKED"] = "|cffff0000Bloqueado|r",
    ["AVAIL"] = "|cff00ff00Disponible|r",
    ["DAYS"] = { [0]="Domingo", [1]="Lunes", [2]="Martes", [3]="Miércoles", [4]="Jueves", [5]="Viernes", [6]="Sábado" },
    ["OPT_TITLE"] = "Configuración de Tiempo",
    ["OPT_R40"] = "Raids 40 (Ciclo Global)",
    ["OPT_ONY"] = "Guarida de Onyxia",
    ["OPT_KARA"] = "Karazhan",
    ["OPT_R20"] = "Raids 20 (Ciclo Global)",
    ["OPT_LANG"] = "Idioma:",
    ["LABEL_DAYS"] = "Días",
    ["LABEL_HOURS"] = "Horas",
    ["LABEL_MINUTES"] = "Minutos",
    ["BTN_SAVE"] = "Guardar",
    ["BTN_CANCEL"] = "Cancelar",
    ["TO_SET"] = "Config.",
    ["SCAN_MC"] = "Núcleo de Magma",
    ["SCAN_BWL"] = "Guarida de Alanegra",
    ["SCAN_AQ40"] = "Templo de Ahn'Qiraj",
    ["SCAN_NAXX"] = "Naxxramas",
    ["SCAN_ES"] = "Santuario Esmeralda", -- Ajout ES
    ["SCAN_ONY"] = "Onyxia",
    ["SCAN_KARA"] = "Karazhan",
    ["SCAN_ZG"] = "Zul'Gurub",
    ["SCAN_AQ20"] = "Ruinas de Ahn'Qiraj",
}